import type { Category } from '../../types/Category'
import type { Professional } from '../../types/Professional'

export const professionals: Professional[] = [
    {
        id: 1,
        name: 'Martín Rodríguez',
        profession: 'Electricista',
        rating: 4.9,
        reviewCount: 124,
        neighborhood: 'Cordón',
        distanceKm: 1.8,
        availability: 'Disponible mañana',
        startingPrice: 1200,
        avatarUrl: '',
    },
    {
        id: 2,
        name: 'Laura Méndez',
        profession: 'Sanitaria',
        rating: 4.8,
        reviewCount: 96,
        neighborhood: 'Pocitos',
        distanceKm: 2.1,
        availability: 'Disponible hoy',
        startingPrice: 1000,
        avatarUrl: '',
    },
    {
        id: 3,
        name: 'Diego Villar',
        profession: 'Pintor',
        rating: 4.7,
        reviewCount: 80,
        neighborhood: 'Parque Rodó',
        distanceKm: 2.5,
        availability: 'Disponible hoy',
        startingPrice: 900,
        avatarUrl: '',
    },
    {
        id: 4,
        name: 'Federico Almeida',
        profession: 'Carpintero',
        rating: 4.9,
        reviewCount: 112,
        neighborhood: 'Centro',
        distanceKm: 1.4,
        availability: 'Disponible mañana',
        startingPrice: 1500,
        avatarUrl: '',
    },
    {
        id: 5,
        name: 'Natalia Suárez',
        profession: 'Jardinera',
        rating: 4.8,
        reviewCount: 73,
        neighborhood: 'Malvín',
        distanceKm: 3.2,
        availability: 'Disponible hoy',
        startingPrice: 1000,
        avatarUrl: '',
    },
    {
        id: 6,
        name: 'Andrés Pereira',
        profession: 'Cerrajero',
        rating: 4.6,
        reviewCount: 58,
        neighborhood: 'La Blanqueada',
        distanceKm: 2.9,
        availability: 'Disponible mañana',
        startingPrice: 1300,
        avatarUrl: '',
    },
    {
        id: 7,
        name: 'Sofía Ramos',
        profession: 'Electricista',
        rating: 4.9,
        reviewCount: 101,
        neighborhood: 'Punta Carretas',
        distanceKm: 1.6,
        availability: 'Disponible hoy',
        startingPrice: 1200,
        avatarUrl: '',
    },
    {
        id: 8,
        name: 'Julián Castro',
        profession: 'Pintor',
        rating: 4.7,
        reviewCount: 64,
        neighborhood: 'Buceo',
        distanceKm: 3.4,
        availability: 'Disponible mañana',
        startingPrice: 900,
        avatarUrl: '',
    },
]

export const categories: Category[] = [
    {
        label: 'Electricidad',
        backgroundColor: '#FFF4C2',
        accentColor: '#C99A00',
        icon: 'wrench',
    },
    {
        label: 'Sanitaria',
        backgroundColor: '#DDF2FF',
        accentColor: '#3182CE',
        icon: 'location',
    },
    {
        label: 'Pintura',
        backgroundColor: '#FFE1E6',
        accentColor: '#D65A73',
        icon: 'star',
    },
    {
        label: 'Cerrajería',
        backgroundColor: '#E9E2FF',
        accentColor: '#7B61C9',
        icon: 'document',
    },
    {
        label: 'Carpintería',
        backgroundColor: '#F7E5D1',
        accentColor: '#A66A32',
        icon: 'wrench',
    },
    {
        label: 'Jardinería',
        backgroundColor: '#DDF3DE',
        accentColor: '#4F8F52',
        icon: 'location',
    },
    {
        label: 'Ver todos',
        backgroundColor: '#EEF1F4',
        accentColor: '#6B7280',
        icon: 'document',
    },
]

export const popularSearches = [
    'Electricista',
    'Plomero',
    'Pintor',
    'Cerrajero',
    'Reparación de calefón',
]
