version: 2
updates:
  # 1. Frontend (React / npm)
  - package-ecosystem: "npm"
    directory: "/frontend" # Cambia por la carpeta donde está tu package.json (o "/" si está en la raíz)
    schedule:
      interval: "weekly"
    target-branch: "dev"

  # 2. Backend (Java Spring / Maven)
  # Nota: si usas Gradle en lugar de Maven, cambia "maven" por "gradle"
  - package-ecosystem: "maven"
    directory: "/backend" # Cambia por la carpeta donde está tu pom.xml o build.gradle
    schedule:
      interval: "weekly"
    target-branch: "dev"

  # 3. Docker Compose (imágenes base de los servicios)
  - package-ecosystem: "docker-compose"
    directory: "/" # Carpeta donde se encuentra tu docker-compose.yml
    schedule:
      interval: "weekly"
    target-branch: "dev"
